import { faAngleDown, faAngleRight, faMinus, faPlus, faQuestionCircle } from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { useState } from "react"
import { ShopInfo } from "../../types/Shops"
import { WatchOptions } from "../../types/Watch"
import Button from "../_utils/Button"
import TextInput from "../_utils/TextInput"
import Tooltip from "../_utils/Tooltip"

export default function WatchOptionsForm ({ shop, watchOptions, update }: { shop: ShopInfo, watchOptions: WatchOptions, update: (options: WatchOptions) => void }) {
  const [isOpen, setIsOpen] = useState(false)
  const [searchToAdd, setSearchToAdd] = useState('')
  const [mustContainToAdd, setMustContainToAdd] = useState('')
  const [excludeToAdd, setExcludeToAdd] = useState('')

  function addSearch() {
    if (watchOptions.searches.length >= 3) return

    if (watchOptions.searches.includes(searchToAdd)) return

    const searches = [...watchOptions.searches, searchToAdd]

    update({ ...watchOptions, searches })

    setSearchToAdd('')

    return
  }

  function addMustContain() {
    if (watchOptions.mustContain.includes(mustContainToAdd)) return

    update({ ...watchOptions, mustContain: [...watchOptions.mustContain, mustContainToAdd] })

    setMustContainToAdd('')

    return
  }

  function addExclude() {
    if (watchOptions.exclude.includes(excludeToAdd)) return

    update({ ...watchOptions, exclude: [...watchOptions.exclude, excludeToAdd] })

    setExcludeToAdd('')

    return
  }

  function removeSearch(e: React.SyntheticEvent, index: number) {
    e.preventDefault()

    const searches = watchOptions.searches

    searches.splice(index, 1)

    update({ ...watchOptions, searches })

    return
  }

  function removeMustContain(e: React.SyntheticEvent, index: number) {
    e.preventDefault()

    const mustContain = watchOptions.mustContain

    mustContain.splice(index, 1)

    update({ ...watchOptions, mustContain })

    return
  }

  function removeExclude(e: React.SyntheticEvent, index: number) {
    e.preventDefault()

    const exclude = watchOptions.exclude

    exclude.splice(index, 1)

    update({ ...watchOptions, exclude })

    return
  }

  return (
    <div className="relative flex flex-col px-2 py-1 rounded-md shadow-md bg-zinc-100 dark:bg-zinc-700 divide-y divide-zinc-300 dark:divide-zinc-500">
      <div className={`flex justify-between ${ isOpen ? 'mb-1' : ''} text-lg cursor-pointer`} onClick={() => setIsOpen(prev => !prev)}>
        <p>
          {shop.name}
        </p>
        <p>
          <FontAwesomeIcon icon={isOpen ? faAngleDown : faAngleRight} />
        </p>
      </div>
      {
        isOpen && (
          <>
            <div className="mb-2 pt-1">
              <div className="flex flex-col mb-2 gap-2">
                <h4 className="flex items-center font-bold">
                  <span className="mr-2">
                    Custom searches
                  </span>
                  <Tooltip
                    icon={faQuestionCircle}
                    info="Queries used to search for the item directly in the shop's search engine. Replace the default strings generated by the algorithm."
                  />
                </h4>
                {
                  !!watchOptions.searches.length ? (
                    watchOptions.searches.map((search, index) => (
                      <p key={search} className="flex justify-between px-2 py-1 rounded-md shadow-md bg-white dark:bg-zinc-800">
                        <span title={search} className="line-clamp-1">{search}</span>
                        <a href="#" title="Remove the search" className="ml-2 text-red-500" onClick={(e) => removeSearch(e, index)}>
                          <FontAwesomeIcon icon={faMinus} />
                        </a>
                      </p>
                    ))
                  ) : (
                    <p className="w-full p-2 text-center text-zinc-500">
                      No searches yet
                    </p>
                  )
                }
              </div>
              {
                watchOptions.searches.length < 3 && (
                  <>
                    <label className="text-sm" htmlFor="AddSearchInput">
                      Add a custom search (3 max.)
                    </label>
                    <div className="flex">
                      <TextInput
                        className="grow"
                        name="AddSearchInput"
                        type="text"
                        bgColor="bg-white dark:bg-zinc-800"
                        value={searchToAdd}
                        update={(value) => setSearchToAdd(value)}
                        enter={() => addSearch()}
                        standalone={false}
                      />
                      <Button title="Add search to the list" action={() => addSearch()}>
                        <FontAwesomeIcon icon={faPlus} />
                      </Button>
                    </div>
                  </>
                )
              }
            </div>
            <div className="mb-2 pt-1">
              <div className="flex flex-col mb-2 gap-2">
                <h4 className="flex items-center font-bold">
                  <span className="mr-2">
                    Must contain
                  </span>
                  <Tooltip
                    icon={faQuestionCircle}
                    info="Terms that must be included in the result's title. Results will be selected solely according to those terms and no longer by our algorithm."
                  />
                </h4>
                <div className="flex flex-wrap justify-start gap-2">
                  {
                    !!watchOptions.mustContain.length ? (
                      watchOptions.mustContain.map((term, index) => (
                        <p key={term} className="flex justify-between px-2 py-1 rounded-md shadow-md bg-white dark:bg-zinc-800">
                          <span>{term}</span>
                          <a href="#" title="Remove the term" className="ml-2 text-red-500" onClick={(e) => removeMustContain(e, index)}>
                            <FontAwesomeIcon icon={faMinus} />
                          </a>
                        </p>
                      ))
                    ) : (
                      <p className="w-full p-2 text-center text-zinc-500">
                        No terms yet
                      </p>
                    )
                  }
                </div>
              </div>
              <label className="text-sm" htmlFor="AddMustContainInput">
                Add a required term (case insensitive)
              </label>
              <div className="flex">
                <TextInput
                  className="grow"
                  name="AddMustContainInput"
                  type="text"
                  bgColor="bg-white dark:bg-zinc-800"
                  value={mustContainToAdd}
                  update={(value) => setMustContainToAdd(value)}
                  enter={() => addMustContain()}
                  standalone={false}
                />
                <Button title="Add term to the list" action={() => addMustContain()}>
                  <FontAwesomeIcon icon={faPlus} />
                </Button>
              </div>
            </div>
            <div className="mb-1 pt-1">
              <div className="flex flex-col mb-2 gap-2">
                <h4 className="flex items-center font-bold">
                  <span className="mr-2">
                    Exclude
                  </span>
                  <Tooltip
                    icon={faQuestionCircle}
                    info="Terms that must not be included in the result's title. Results will be filtered out solely according to those terms and no longer by our algorithm."
                  />
                </h4>
                <div className="flex flex-wrap justify-start gap-2">
                  {
                    !!watchOptions.exclude.length ? (
                      watchOptions.exclude.map((term, index) => (
                        <p key={term} className="flex justify-between px-2 py-1 rounded-md shadow-md bg-white dark:bg-zinc-800">
                          <span>{term}</span>
                          <a href="#" title="Remove the term" className="ml-2 text-red-500" onClick={(e) => removeExclude(e, index)}>
                            <FontAwesomeIcon icon={faMinus} />
                          </a>
                        </p>
                      ))
                    ) : (
                      <p className="w-full p-2 text-center text-zinc-500">
                        No terms yet
                      </p>
                    )
                  }
                </div>
              </div>
              <label className="text-sm" htmlFor="AddMustContainInput">
                Add an excluded term (case insensitive)
              </label>
              <div className="flex">
                <TextInput
                  className="grow"
                  name="AddExcludeInput"
                  type="text"
                  bgColor="bg-white dark:bg-zinc-800"
                  value={excludeToAdd}
                  update={(value) => setExcludeToAdd(value)}
                  enter={() => addExclude()}
                  standalone={false}
                />
                <Button title="Add term to the list" action={() => addExclude()}>
                  <FontAwesomeIcon icon={faPlus} />
                </Button>
              </div>
            </div>
          </>
        )
      }
    </div>
  )
}
